name: fakestore_one
description: test app with freezed and bloc and chopper
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  stream_transform: ^2.0.0
  provider: ^6.0.3

  json_serializable: ^6.4.1
  build_runner: ^2.2.1


dev_dependencies:
  freezed_annotation: ^2.1.0
  freezed: ^2.1.1

flutter:
  uses-material-design: true
